portalRecipes:
  - existingPortals: '0'
    recipe:
        - id: 'minecraft:air'
          count: 0
        - id: 'minecraft:air'
          count: 0
        - id: 'minecraft:air'
          count: 0
        - id: 'minecraft:air'
          count: 0
        - id: 'minecraft:dirt'
          count: 3
        - id: 'minecraft:air'
          count: 0
        - id: 'minecraft:air'
          count: 0
        - id: 'minecraft:air'
          count: 0
        - id: 'minecraft:air'
          count: 0
  - existingPortals: '1-'
    recipe:
      - id: 'minecraft:air'
        count: 0
      - id: 'minecraft:air'
        count: 0
      - id: 'minecraft:air'
        count: 0
      - id: 'minecraft:air'
        count: 0
      - id: 'minecraft:prismarine'
        count: 2
      - id: 'minecraft:air'
        count: 0
      - id: 'minecraft:air'
        count: 0
      - id: 'minecraft:air'
        count: 0
      - id: 'minecraft:air'
        count: 0

players: []

portals: []